In [2]:
import numpy as np

In [12]:
arr = np.arange(0, 30, 3)
print(arr)

[ 0  3  6  9 12 15 18 21 24 27]


In [5]:
#retorna elemento no índice 5
arr[5]

15

In [6]:
#do 0 ao 5
arr[0:5]

array([ 0,  3,  6,  9, 12])

In [7]:
#do 4 ao final
arr[4:]

array([12, 15, 18, 21, 24, 27])

In [8]:
#do início ao 5
arr[:5]

array([ 0,  3,  6,  9, 12])

In [11]:
#atribui 100 a todos os elementos à partir da posição 2
arr[2:] = 100
print(arr)

[  0   3 100 100 100 100 100 100 100 100]


In [14]:
#cria um array de 50 números e depois formata no padrão 5 linhas com 10 elementos cada
arr =np.arange(50).reshape(5,10)
print(arr)
print(arr.shape)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
(5, 10)


In [16]:
#fatiamento (primeiro colchete são as linhas, segundo colchete são as colunas)
print(arr[:3][:])
print(arr[:3])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


In [19]:
#cria um segundo array, que vai da linha 0 até a linha 3 de arr, por referência
arr2 = arr[:3]
print(arr2)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


In [20]:
#quando atualiza um array criado por referência, atualiza os dados do array original
arr2[:] = 100
print(arr2)

[[100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]]


In [21]:
print(arr)

[[100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [ 30  31  32  33  34  35  36  37  38  39]
 [ 40  41  42  43  44  45  46  47  48  49]]


In [23]:
#forma correta de criar uma cópia sem a referência ao array original
arr2 = arr[:3].copy()
print(arr2)

[[100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]]


In [24]:
arr2[:] = 50
print(arr2)
print(arr)

[[50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]]
[[100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [ 30  31  32  33  34  35  36  37  38  39]
 [ 40  41  42  43  44  45  46  47  48  49]]


In [30]:
arr =np.arange(50).reshape(5,10)
print(arr)

#outra forma de fatiamento: range de linha, range de coluna
novo_arr = arr[1:4,5:]
print(novo_arr)
print(novo_arr.shape)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[[15 16 17 18 19]
 [25 26 27 28 29]
 [35 36 37 38 39]]
(3, 5)


In [32]:
#realiza a comparação de cada elemento do array que for > 25
arr > 25

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [36]:
#cria uma matriz com a expressão validada para cada elemento (verifica se cada elemento é > 25)
bol = arr > 25
print(bol)
print(bol.shape)

#extrai do array original apenas os elementos do array que são verdadeiros na expressão
#retorna um slice de 1 dimensão
print(arr[bol])


[[False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]]
(5, 10)
[26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [37]:
arr3 = np.linspace(0,100,30)

In [38]:
arr3

array([  0.        ,   3.44827586,   6.89655172,  10.34482759,
        13.79310345,  17.24137931,  20.68965517,  24.13793103,
        27.5862069 ,  31.03448276,  34.48275862,  37.93103448,
        41.37931034,  44.82758621,  48.27586207,  51.72413793,
        55.17241379,  58.62068966,  62.06896552,  65.51724138,
        68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
        82.75862069,  86.20689655,  89.65517241,  93.10344828,
        96.55172414, 100.        ])

In [39]:
arr3.shape

(30,)

In [40]:
arr3 = arr3.reshape(3,10)

In [41]:
arr3

array([[  0.        ,   3.44827586,   6.89655172,  10.34482759,
         13.79310345,  17.24137931,  20.68965517,  24.13793103,
         27.5862069 ,  31.03448276],
       [ 34.48275862,  37.93103448,  41.37931034,  44.82758621,
         48.27586207,  51.72413793,  55.17241379,  58.62068966,
         62.06896552,  65.51724138],
       [ 68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
         82.75862069,  86.20689655,  89.65517241,  93.10344828,
         96.55172414, 100.        ]])

In [43]:
#recupera elementos das linha de 0 a 2 (2 não inclusa), coluna 2
arr3[0:2,2]

array([ 6.89655172, 41.37931034])