In [1]:
import numpy as np

In [2]:
lista = [1,2,3]
lista

[1, 2, 3]

In [3]:
np.array(lista)

array([1, 2, 3])

In [4]:
matriz = [[1,2,3], [4,5,6], [7,8,9]]

In [5]:
np.array(matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
#arange
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [9]:
#matriz de zeros
np.zeros(3)

array([0., 0., 0.])

In [10]:
#matriz de zeros multidimensional
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
#matriz de uns
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
#matriz de identidade
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
#especifica quantos números vc quer na matriz, de um intervalor
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [15]:
#random - aleatórios
np.random.rand(5)

array([0.11888761, 0.1114374 , 0.77808513, 0.72462406, 0.46796547])

In [16]:
np.random.rand(5) * 100

array([50.16781589, 21.44511198, 88.57977644, 41.5276747 , 79.9191191 ])

In [17]:
np.random.rand(5,4)

array([[0.03953069, 0.3685557 , 0.33850507, 0.74831055],
       [0.69019712, 0.66833866, 0.7252698 , 0.9337357 ],
       [0.29309768, 0.08500003, 0.30060008, 0.59557636],
       [0.86120813, 0.05776915, 0.13549122, 0.1777939 ],
       [0.17157971, 0.64318521, 0.46195086, 0.15717978]])

In [18]:
np.random.randn(4)

array([ 0.04558581, -0.14297954, -0.83750565, -0.14527564])

In [19]:
#retorna 10 números inteiros randômicos, de 0 a 100
np.random.randint(0,100,10)

array([52, 68, 40, 94, 92,  6, 75, 17, 73, 95])

In [22]:
np.round(np.random.rand(5)*100,0)

array([14., 77., 70., 24., 98.])

In [26]:
#cria uma matriz de 1 dimensão com 25 números aleatórios
arr = np.random.rand(25)
print(arr)

[0.72216902 0.33434438 0.51685917 0.66938294 0.26743298 0.04584527
 0.85285483 0.32105175 0.82722901 0.21314348 0.13975491 0.47265792
 0.89882759 0.79499763 0.46012691 0.31498505 0.00830052 0.25114855
 0.58219681 0.10658145 0.49619867 0.37488986 0.97500028 0.11067993
 0.03439992]


In [28]:
#formata o array em 5 linhas com 5 colunas
arr_reshape = arr.reshape(5,5)
print(arr_reshape)

[[0.72216902 0.33434438 0.51685917 0.66938294 0.26743298]
 [0.04584527 0.85285483 0.32105175 0.82722901 0.21314348]
 [0.13975491 0.47265792 0.89882759 0.79499763 0.46012691]
 [0.31498505 0.00830052 0.25114855 0.58219681 0.10658145]
 [0.49619867 0.37488986 0.97500028 0.11067993 0.03439992]]


In [31]:
#atributo shape mostra a dimensão do array
print(arr.shape)

(25,)


In [32]:
print(arr_reshape.shape)

(5, 5)


In [33]:
#retorna maior valor do array
arr.max()

0.9750002845272405

In [34]:
#retorna menor valor do array
arr.min()

0.00830052210454535

In [35]:
#retorna o índice do maior valor
arr.argmax()

22

In [36]:
#retorna o índice do menor valor
arr.argmin()

16